# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    
    
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r req.txt
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        Username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: viha27/devopspython_27:latest
      
    - name: Test with pytest
      run: |
        pytest test.py
